"""
services/netlify_service.py
────────────────────────────
Netlify Manager — programmatically creates and configures Netlify sites
for every frontend project generated by AI Factory.

Public API
──────────
  write_netlify_toml(repo_name, backend_url)
      Commits a netlify.toml to the root of a generated GitHub repo.
      Must be called BEFORE create_netlify_site so the correct proxy config
      is already in the repo when Netlify's first build runs.

  create_netlify_site(site_name, repo_full_name)
      Creates a Netlify site linked to the GitHub repo with build settings
      (command: 'npm --prefix frontend install && npm --prefix frontend run build',
       publish directory: 'frontend/dist').
      Does NOT write netlify.toml — that is the caller's responsibility.
      Returns {"site_url": str, "site_id": str} on success or {"error": str} on failure.

Double-Step deployment order (enforced by agent_runner.py)
────────────────────────────────────────────────────────────
  For full-stack projects the caller MUST follow this exact order:

    Step 1 — infrastructure/railway_client.create_production_service()
              → backend_url (the generated project's Railway URL)

    Step 2 — services/netlify_service.write_netlify_toml(repo_name, backend_url)
              → netlify.toml committed to GitHub with real proxy target

    Step 3 — services/netlify_service.create_netlify_site(site_name, repo_full_name)
              → Netlify site created; Netlify reads netlify.toml from GitHub
                on its FIRST build, so the proxy is correct immediately

  This order guarantees that Netlify's first build has the correct proxy
  config — no second build needed.
"""

import logging
import os
from pathlib import Path

import requests
from dotenv import dotenv_values, load_dotenv

_BACKEND_ENV_PATH = Path(__file__).resolve().parents[1] / ".env"
load_dotenv(_BACKEND_ENV_PATH)

logger = logging.getLogger(__name__)

_FRONTEND_BUILD_COMMAND = "npm --prefix frontend install && npm --prefix frontend run build"
_FRONTEND_PUBLISH_DIR   = "frontend/dist"
_VANILLA_PUBLISH_DIR    = "frontend"


def _auth_token() -> str:
    # Prefer runtime environment variables, then fall back to backend/.env values.
    # This makes token resolution robust for long-running processes where .env
    # values may be added after initial import.
    candidates = [
        os.getenv("NETLIFY_AUTH_TOKEN", ""),
        os.getenv("NETLIFY_TOKEN", ""),
        os.getenv("NETLIFY_ACCESS_TOKEN", ""),
    ]

    for value in candidates:
        token = (value or "").strip()
        if token:
            return token

    if _BACKEND_ENV_PATH.exists():
        try:
            file_env = dotenv_values(_BACKEND_ENV_PATH)
        except Exception as exc:
            logger.warning("Failed to parse backend env file at %s: %s", _BACKEND_ENV_PATH, exc)
            file_env = {}

        for key in ("NETLIFY_AUTH_TOKEN", "NETLIFY_TOKEN", "NETLIFY_ACCESS_TOKEN"):
            token = (file_env.get(key) or "").strip()
            if token:
                # Cache for subsequent calls in this process.
                os.environ.setdefault("NETLIFY_AUTH_TOKEN", token)
                return token

    return ""


def _account_slug() -> str:
    """
    Target Netlify account slug for site creation.

    Preferred env var is NETLIFY_ACCOUNT_SLUG.
    NETLIFY_TEAM_ID is kept as a backward-compatible alias.
    """
    return (
        os.getenv("NETLIFY_ACCOUNT_SLUG", "").strip()
        or os.getenv("NETLIFY_TEAM_ID", "").strip()
    )


def _api_base() -> str:
    return os.getenv("NETLIFY_API_BASE_URL", "https://api.netlify.com/api/v1").rstrip("/")


def _headers() -> dict:
    return {
        "Authorization": f"Bearer {_auth_token()}",
        "Content-Type": "application/json",
    }


def _desired_build_settings(repo_full_name: str, is_npm: bool = True) -> dict:
    repo_name = repo_full_name.split("/")[-1] if "/" in repo_full_name else repo_full_name
    return {
        "provider": "github",
        "repo_url": f"https://github.com/{repo_full_name}",
        "repo_path": repo_full_name,
        "repo_branch": "main",
        "allowed_branches": ["main"],
        "public_repo": True,
        "cmd": _FRONTEND_BUILD_COMMAND if is_npm else "",
        "dir": _FRONTEND_PUBLISH_DIR if is_npm else _VANILLA_PUBLISH_DIR,
    }


def _ensure_site_build_settings(site_id: str, repo_full_name: str, is_npm: bool = True) -> bool:
    """
    Force site build settings to match this codebase structure.

    Generated repos keep web code in /frontend, so Netlify must build from there.
    """
    if not site_id:
        return False

    url = f"{_api_base()}/sites/{site_id}"
    # Set public_repo in BOTH build_settings and the top-level repo object so
    # Netlify's clone step uses anonymous HTTPS instead of SSH deploy keys.
    payload = {
        "build_settings": _desired_build_settings(repo_full_name, is_npm=is_npm),
        "repo": {
            "provider": "github",
            "repo": repo_full_name,
            "branch": "main",
            "public_repo": True,
        },
    }

    try:
        resp = requests.patch(url, json=payload, headers=_headers(), timeout=30)
    except requests.RequestException as exc:
        logger.warning("Failed to update Netlify build settings for site %s: %s", site_id, exc)
        return False

    if resp.status_code in (200, 201):
        logger.info(
            "Updated Netlify build settings for site %s (repo=%s, cmd=%s, dir=%s, public_repo=true).",
            site_id,
            repo_full_name,
            _FRONTEND_BUILD_COMMAND,
            _FRONTEND_PUBLISH_DIR,
        )
        return True

    logger.warning(
        "Failed to update Netlify build settings for site %s (HTTP %s): %s",
        site_id,
        resp.status_code,
        resp.text[:300],
    )
    return False


def _find_existing_site_for_repo(repo_full_name: str, site_name: str | None = None) -> dict | None:
    """
    Best-effort lookup for an existing Netlify site already linked to repo_full_name.

    This prevents repeated /sites create failures for repos that are already connected.
    """
    # First try account-scoped listing when configured, then fall back to global.
    account_slug = _account_slug()
    urls = []
    if account_slug:
        urls.append(f"{_api_base()}/{account_slug}/sites")
    urls.append(f"{_api_base()}/sites")

    sites: list[dict] = []
    fetched_any = False
    for url in urls:
        try:
            resp = requests.get(url, headers=_headers(), timeout=30)
        except requests.RequestException as exc:
            logger.warning("Failed to query Netlify sites list at %s: %s", url, exc)
            continue

        if resp.status_code != 200:
            logger.warning(
                "Failed to list Netlify sites at %s (HTTP %s): %s",
                url,
                resp.status_code,
                resp.text[:240],
            )
            continue

        try:
            data = resp.json()
        except ValueError:
            logger.warning("Netlify sites list returned non-JSON response at %s.", url)
            continue

        if isinstance(data, list):
            sites = data
            fetched_any = True
            break

    if not fetched_any:
        return None

    target_repo = repo_full_name.strip().lower()
    target_name = (site_name or "").strip().lower()

    for site in sites:
        linked_repo = ((site.get("repo") or {}).get("repo") or "").strip().lower()
        if linked_repo and linked_repo == target_repo:
            logger.info(
                "Found existing Netlify site '%s' already linked to %s.",
                site.get("name", "?"),
                repo_full_name,
            )
            return _parse_site_response(site, repo_full_name)

    if target_name:
        for site in sites:
            if (site.get("name") or "").strip().lower() == target_name:
                logger.info(
                    "Found existing Netlify site by name '%s' for repo lookup fallback.",
                    site.get("name", "?"),
                )
                return _parse_site_response(site, repo_full_name)

    return None


# ── netlify.toml ──────────────────────────────────────────────────────────────

def _repo_has_package_json(repo_name: str) -> bool:
    """Return True if frontend/package.json exists in the repo (npm-based project)."""
    from services.github_service import read_file_from_repo
    try:
        content = read_file_from_repo(repo_name, "frontend/package.json")
        return content is not None
    except Exception:
        return False


def write_netlify_toml(repo_name: str, backend_url: str | None = None) -> bool:
    """
    Commit a netlify.toml to the root of the generated GitHub repo.

    Automatically detects whether the project is npm-based (has frontend/package.json)
    or vanilla HTML/CSS/JS (no package.json):

    - npm project  → build command + frontend/dist publish dir
    - vanilla JS   → no build command, publish frontend/ directly

    Optionally adds a server-side /api/* proxy to the Railway backend URL.
    MUST be called before create_netlify_site.

    Args:
        repo_name:   Short GitHub repo name (e.g. "my-recipe-app").
        backend_url: The generated project's Railway HTTPS URL (optional).

    Returns True on success, False on failure.
    """
    from services.github_service import write_file_to_repo

    is_npm = _repo_has_package_json(repo_name)
    logger.info(
        "netlify.toml for %s: detected %s project.",
        repo_name,
        "npm/framework" if is_npm else "vanilla HTML/CSS/JS",
    )

    if is_npm:
        toml = (
            "[build]\n"
            f'  command = "{_FRONTEND_BUILD_COMMAND}"\n'
            f'  publish = "{_FRONTEND_PUBLISH_DIR}"\n'
        )
    else:
        # Vanilla HTML/CSS/JS — no build step, serve files directly.
        toml = (
            "[build]\n"
            f'  publish = "{_VANILLA_PUBLISH_DIR}"\n'
        )

    if backend_url:
        clean_backend = backend_url.rstrip("/")
        toml += (
            "\n"
            "# Proxy /api/* to this project's Railway backend.\n"
            "# Server-side rewrite (status=200) — browser never sees a cross-origin request.\n"
            "[[redirects]]\n"
            '  from   = "/api/*"\n'
            f'  to     = "{clean_backend}/api/:splat"\n'
            "  status = 200\n"
            "  force  = true\n"
        )

    ok = write_file_to_repo(
        repo_name=repo_name,
        file_path="netlify.toml",
        content=toml,
        branch="main",
        commit_message="AI Agent: add netlify.toml with Railway API proxy",
    )
    if ok:
        logger.info(
            "netlify.toml committed to %s (proxy → %s).", repo_name, backend_url,
        )
    else:
        logger.warning("Failed to write netlify.toml to %s.", repo_name)
    return ok


# ── Netlify site creation ─────────────────────────────────────────────────────

def create_netlify_site(
    site_name: str,
    repo_full_name: str,
) -> dict:
    """
    Create a Netlify site linked to the GitHub repo, configured for CD.

        Netlify triggers a new deploy on every push to the main branch.
        Build settings:
            command='npm --prefix frontend install && npm --prefix frontend run build'
            publish directory='frontend/dist'.

    Does NOT write netlify.toml — that must already be committed to the repo
    before this function is called (see write_netlify_toml).

    Args:
        site_name:       Desired Netlify subdomain slug (e.g. "recipe-app").
                         Netlify appends .netlify.app → https://recipe-app.netlify.app
                         Falls back to an auto-assigned name on 422 name conflict.
        repo_full_name:  GitHub "org/repo" identifier
                         (e.g. "AI-Factory-Repos/recipe-app").

    Returns:
        {"site_url": str, "site_id": str}  on success.
        {"error": str}                     on failure.
    """
    token = _auth_token()
    if not token:
        message = (
            "NETLIFY auth token is missing. Checked NETLIFY_AUTH_TOKEN, "
            "NETLIFY_TOKEN, NETLIFY_ACCESS_TOKEN, and backend/.env. "
            f"Skipping Netlify site creation for '{site_name}'."
        )
        logger.error(message)
        return {"error": message}

    # Detect project type once — used for build settings throughout.
    repo_name = repo_full_name.split("/")[-1] if "/" in repo_full_name else repo_full_name
    is_npm = _repo_has_package_json(repo_name)

    # Fast path: if this repo is already linked, reuse the existing site.
    existing = _find_existing_site_for_repo(repo_full_name, site_name)
    if existing:
        _ensure_site_build_settings(existing.get("site_id", ""), repo_full_name, is_npm=is_npm)
        return existing

    account_slug = _account_slug()
    build_cmd = _FRONTEND_BUILD_COMMAND if is_npm else ""
    publish_dir = _FRONTEND_PUBLISH_DIR if is_npm else _VANILLA_PUBLISH_DIR

    payload: dict = {
        "name": site_name,
        "repo": {
            "provider": "github",
            "repo":     repo_full_name,
            "branch":   "main",
            "cmd":      build_cmd,
            "dir":      publish_dir,
            "public_repo": True,
        },
        "build_settings": _desired_build_settings(repo_full_name, is_npm=is_npm),
    }

    # Account-specific endpoint guarantees the site appears in the intended team.
    # If no slug is configured, default to the token owner's personal scope.
    url = (
        f"{_api_base()}/{account_slug}/sites"
        if account_slug
        else f"{_api_base()}/sites"
    )
    logger.info(
        "Creating Netlify site '%s' linked to %s (account=%s) …",
        site_name, repo_full_name, account_slug or "personal",
    )

    try:
        resp = requests.post(url, json=payload, headers=_headers(), timeout=30)
    except requests.RequestException as exc:
        message = f"Netlify API request failed for '{site_name}': {exc}"
        logger.error(message)
        return {"error": message}

    if resp.status_code in (200, 201):
        parsed = _parse_site_response(resp.json(), repo_full_name)
        _ensure_site_build_settings(parsed.get("site_id", ""), repo_full_name, is_npm=is_npm)
        return parsed

    # 422 = subdomain already taken — retry without a name so Netlify auto-assigns
    if resp.status_code == 422:
        logger.warning(
            "Netlify site name '%s' already taken — retrying with auto-assigned name.",
            site_name,
        )
        payload.pop("name", None)
        try:
            retry = requests.post(url, json=payload, headers=_headers(), timeout=30)
        except requests.RequestException as exc:
            message = f"Netlify retry request failed: {exc}"
            logger.error(message)
            return {"error": message}

        if retry.status_code in (200, 201):
            parsed = _parse_site_response(retry.json(), repo_full_name)
            _ensure_site_build_settings(parsed.get("site_id", ""), repo_full_name, is_npm=is_npm)
            return parsed

        existing_after_retry = _find_existing_site_for_repo(repo_full_name, site_name)
        if existing_after_retry:
            _ensure_site_build_settings(existing_after_retry.get("site_id", ""), repo_full_name, is_npm=is_npm)
            return existing_after_retry

        message = (
            f"Failed to create Netlify site '{site_name}' after 422 retry "
            f"(HTTP {retry.status_code}): {retry.text[:400]}"
        )
        logger.error(message)
        return {"error": message}

    # Last chance: check whether a linked site already exists for this repo.
    existing_after_failure = _find_existing_site_for_repo(repo_full_name, site_name)
    if existing_after_failure:
        _ensure_site_build_settings(existing_after_failure.get("site_id", ""), repo_full_name, is_npm=is_npm)
        return existing_after_failure

    message = (
        f"Failed to create Netlify site '{site_name}': HTTP {resp.status_code} — "
        f"{resp.text[:400]}"
    )
    logger.error(message)
    return {"error": message}


def _parse_site_response(data: dict, repo_full_name: str) -> dict:
    site_id   = data.get("id", "")
    site_name = data.get("name", "")
    site_url  = (
        data.get("ssl_url")
        or data.get("url")
        or f"https://{site_name}.netlify.app"
    )
    logger.info(
        "Netlify site ready: %s (id=%s, repo=%s).",
        site_url, site_id, repo_full_name,
    )
    return {"site_url": site_url, "site_id": site_id}
