"""
services/netlify_service.py
────────────────────────────
Netlify Manager — programmatically creates and configures Netlify sites
for every frontend project generated by AI Factory.

Public API
──────────
  write_netlify_toml(repo_name, backend_url)
      Commits a netlify.toml to the root of a generated GitHub repo.
      Must be called BEFORE create_netlify_site so the correct proxy config
      is already in the repo when Netlify's first build runs.

  create_netlify_site(site_name, repo_full_name)
      Creates a Netlify site linked to the GitHub repo with build settings
      (command: 'npm run build', publish directory: 'dist').
      Does NOT write netlify.toml — that is the caller's responsibility.
      Returns {"site_url": str, "site_id": str} on success or {"error": str} on failure.

Double-Step deployment order (enforced by agent_runner.py)
────────────────────────────────────────────────────────────
  For full-stack projects the caller MUST follow this exact order:

    Step 1 — infrastructure/railway_client.create_production_service()
              → backend_url (the generated project's Railway URL)

    Step 2 — services/netlify_service.write_netlify_toml(repo_name, backend_url)
              → netlify.toml committed to GitHub with real proxy target

    Step 3 — services/netlify_service.create_netlify_site(site_name, repo_full_name)
              → Netlify site created; Netlify reads netlify.toml from GitHub
                on its FIRST build, so the proxy is correct immediately

  This order guarantees that Netlify's first build has the correct proxy
  config — no second build needed.
"""

import logging
import os
from pathlib import Path

import requests
from dotenv import load_dotenv

_BACKEND_ENV_PATH = Path(__file__).resolve().parents[1] / ".env"
load_dotenv(_BACKEND_ENV_PATH)

logger = logging.getLogger(__name__)


def _auth_token() -> str:
    return os.getenv("NETLIFY_AUTH_TOKEN", "")


def _account_slug() -> str:
    """
    Target Netlify account slug for site creation.

    Preferred env var is NETLIFY_ACCOUNT_SLUG.
    NETLIFY_TEAM_ID is kept as a backward-compatible alias.
    """
    return (
        os.getenv("NETLIFY_ACCOUNT_SLUG", "").strip()
        or os.getenv("NETLIFY_TEAM_ID", "").strip()
    )


def _api_base() -> str:
    return os.getenv("NETLIFY_API_BASE_URL", "https://api.netlify.com/api/v1").rstrip("/")


def _headers() -> dict:
    return {
        "Authorization": f"Bearer {_auth_token()}",
        "Content-Type": "application/json",
    }


def _find_existing_site_for_repo(repo_full_name: str, site_name: str | None = None) -> dict | None:
    """
    Best-effort lookup for an existing Netlify site already linked to repo_full_name.

    This prevents repeated /sites create failures for repos that are already connected.
    """
    # First try account-scoped listing when configured, then fall back to global.
    account_slug = _account_slug()
    urls = []
    if account_slug:
        urls.append(f"{_api_base()}/{account_slug}/sites")
    urls.append(f"{_api_base()}/sites")

    sites: list[dict] = []
    fetched_any = False
    for url in urls:
        try:
            resp = requests.get(url, headers=_headers(), timeout=30)
        except requests.RequestException as exc:
            logger.warning("Failed to query Netlify sites list at %s: %s", url, exc)
            continue

        if resp.status_code != 200:
            logger.warning(
                "Failed to list Netlify sites at %s (HTTP %s): %s",
                url,
                resp.status_code,
                resp.text[:240],
            )
            continue

        try:
            data = resp.json()
        except ValueError:
            logger.warning("Netlify sites list returned non-JSON response at %s.", url)
            continue

        if isinstance(data, list):
            sites = data
            fetched_any = True
            break

    if not fetched_any:
        return None

    target_repo = repo_full_name.strip().lower()
    target_name = (site_name or "").strip().lower()

    for site in sites:
        linked_repo = ((site.get("repo") or {}).get("repo") or "").strip().lower()
        if linked_repo and linked_repo == target_repo:
            logger.info(
                "Found existing Netlify site '%s' already linked to %s.",
                site.get("name", "?"),
                repo_full_name,
            )
            return _parse_site_response(site, repo_full_name)

    if target_name:
        for site in sites:
            if (site.get("name") or "").strip().lower() == target_name:
                logger.info(
                    "Found existing Netlify site by name '%s' for repo lookup fallback.",
                    site.get("name", "?"),
                )
                return _parse_site_response(site, repo_full_name)

    return None


# ── netlify.toml ──────────────────────────────────────────────────────────────

def write_netlify_toml(repo_name: str, backend_url: str) -> bool:
    """
    Commit a netlify.toml to the root of the generated GitHub repo.

    The toml sets the Vite build command/publish dir and adds a server-side
    /api/* proxy rule pointing at the generated project's Railway backend URL.
    The server-side rewrite (status=200, force=true) means the browser never
    makes a cross-origin request — no CORS issues.

    MUST be called before create_netlify_site so Netlify uses this config
    on its first build.

    Args:
        repo_name:   Short GitHub repo name (e.g. "my-recipe-app").
        backend_url: The generated project's Railway HTTPS URL
                     (from infrastructure/railway_client.create_production_service).

    Returns True on success, False on failure.
    """
    from services.github_service import write_file_to_repo

    clean_backend = backend_url.rstrip("/")
    toml = (
        "[build]\n"
        '  command = "npm run build"\n'
        '  publish = "dist"\n'
        "\n"
        "# Proxy /api/* to this project's Railway backend.\n"
        "# Server-side rewrite (status=200) — browser never sees a cross-origin request.\n"
        "[[redirects]]\n"
        '  from   = "/api/*"\n'
        f'  to     = "{clean_backend}/api/:splat"\n'
        "  status = 200\n"
        "  force  = true\n"
    )

    ok = write_file_to_repo(
        repo_name=repo_name,
        file_path="netlify.toml",
        content=toml,
        branch="main",
        commit_message="AI Agent: add netlify.toml with Railway API proxy",
    )
    if ok:
        logger.info(
            "netlify.toml committed to %s (proxy → %s).", repo_name, backend_url,
        )
    else:
        logger.warning("Failed to write netlify.toml to %s.", repo_name)
    return ok


# ── Netlify site creation ─────────────────────────────────────────────────────

def create_netlify_site(
    site_name: str,
    repo_full_name: str,
) -> dict:
    """
    Create a Netlify site linked to the GitHub repo, configured for CD.

    Netlify triggers a new deploy on every push to the main branch.
    Build settings: command='npm run build', publish directory='dist'.

    Does NOT write netlify.toml — that must already be committed to the repo
    before this function is called (see write_netlify_toml).

    Args:
        site_name:       Desired Netlify subdomain slug (e.g. "recipe-app").
                         Netlify appends .netlify.app → https://recipe-app.netlify.app
                         Falls back to an auto-assigned name on 422 name conflict.
        repo_full_name:  GitHub "org/repo" identifier
                         (e.g. "AI-Factory-Repos/recipe-app").

    Returns:
        {"site_url": str, "site_id": str}  on success.
        {"error": str}                     on failure.
    """
    token = _auth_token()
    if not token:
        message = (
            "NETLIFY_AUTH_TOKEN is not set — skipping Netlify site creation for "
            f"'{site_name}'."
        )
        logger.error(message)
        return {"error": message}

    # Fast path: if this repo is already linked, reuse the existing site.
    existing = _find_existing_site_for_repo(repo_full_name, site_name)
    if existing:
        return existing

    account_slug = _account_slug()

    payload: dict = {
        "name": site_name,
        "repo": {
            "provider": "github",
            "repo":     repo_full_name,
            "branch":   "main",
            "cmd":      "npm run build",
            "dir":      "dist",
        },
    }

    # Account-specific endpoint guarantees the site appears in the intended team.
    # If no slug is configured, default to the token owner's personal scope.
    url = (
        f"{_api_base()}/{account_slug}/sites"
        if account_slug
        else f"{_api_base()}/sites"
    )
    logger.info(
        "Creating Netlify site '%s' linked to %s (account=%s) …",
        site_name, repo_full_name, account_slug or "personal",
    )

    try:
        resp = requests.post(url, json=payload, headers=_headers(), timeout=30)
    except requests.RequestException as exc:
        message = f"Netlify API request failed for '{site_name}': {exc}"
        logger.error(message)
        return {"error": message}

    if resp.status_code in (200, 201):
        return _parse_site_response(resp.json(), repo_full_name)

    # 422 = subdomain already taken — retry without a name so Netlify auto-assigns
    if resp.status_code == 422:
        logger.warning(
            "Netlify site name '%s' already taken — retrying with auto-assigned name.",
            site_name,
        )
        payload.pop("name", None)
        try:
            retry = requests.post(url, json=payload, headers=_headers(), timeout=30)
        except requests.RequestException as exc:
            message = f"Netlify retry request failed: {exc}"
            logger.error(message)
            return {"error": message}

        if retry.status_code in (200, 201):
            return _parse_site_response(retry.json(), repo_full_name)

        # Repo may already be linked to a site despite 422 on create.
        existing_after_retry = _find_existing_site_for_repo(repo_full_name, site_name)
        if existing_after_retry:
            return existing_after_retry

        message = (
            f"Failed to create Netlify site '{site_name}' after 422 retry "
            f"(HTTP {retry.status_code}): {retry.text[:400]}"
        )
        logger.error(message)
        return {"error": message}

    # Last chance: check whether a linked site already exists for this repo.
    existing_after_failure = _find_existing_site_for_repo(repo_full_name, site_name)
    if existing_after_failure:
        return existing_after_failure

    message = (
        f"Failed to create Netlify site '{site_name}': HTTP {resp.status_code} — "
        f"{resp.text[:400]}"
    )
    logger.error(message)
    return {"error": message}


def _parse_site_response(data: dict, repo_full_name: str) -> dict:
    site_id   = data.get("id", "")
    site_name = data.get("name", "")
    site_url  = (
        data.get("ssl_url")
        or data.get("url")
        or f"https://{site_name}.netlify.app"
    )
    logger.info(
        "Netlify site ready: %s (id=%s, repo=%s).",
        site_url, site_id, repo_full_name,
    )
    return {"site_url": site_url, "site_id": site_id}
